config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :links
   resources :statics
   root 'links#index'
   
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :link_tags, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :link_tags, dependent: :destroy
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
  belongs_to :link
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
 #Tagsテーブルから中間テーブルに対する関連付け
  has_many :link_tags, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :links, through: :link_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

 before_action :authenticate_user!, only: [:new, :create]

  def index
     @links = Link.all
    if params[:search] == nil
        @links = Link.all
      elsif params[:search] == ''
       @links = Link.all
      else
        #部分検索
        @links = Link.where("title LIKE ? ",'%' + params[:search] + '%')
        @links = Link.where("memo LIKE ? ",'%' + params[:search] + '%')
    end

    if params[:tag_ids] 
      @links = [] 
      params[:tag_ids].each do |key, value| 
        if value == "1" 
         tag_links = Tag.find_by(tname: key).links 
         @links = @links.empty? ? tag_links : @links & tag_links 
        end 
      end 
    end

   if params[:tag]
     Tag.create(tname: params[:tag]) 
   end 
  end 


  def new
    @link = Link.new
  end

  def create
    link = Link.new(link_params)
    if link.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    link = Link.find(params[:id])
    if link.update(link_params)
      redirect_to :action => "show", :id => link.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    link = Link.find(params[:id])
    link.destroy
    redirect_to action: :index
  end

  private
  def link_params
    params.require(:link).permit(:folder_id, :url, :title, :memo)
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>linfo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
 <header>
  <h1>linfo</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/links/edit.html.erb
<%= form_for @link do |f| %>
  <%= f.label :編集ページ %>
  <%= f.text_field :url, :size => 140 %> 
  <%= f.text_field :title, :size => 140 %> 
  <%= f.text_field :memo, :size => 140 %> 
  <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tname) do |tag| %>
      <div class='form-check'>
       <%= tag.label class: 'form-check-label' do %>
       <%= tag.check_box class: 'form-check-input' %>
       <%= tag.text %>
       <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit "保存する" %>
<% end %>

app/views/links/index.html.erb
<h1>linfo</h1>

<h3>一覧ページ</h3>

<h4>タイトル・メモから検索</h4>
 <%= form_tag({controller:"links",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する'  %>
<% end %>


<h4>タグで絞り込み</h4>
 <% Tag.all.each do |t| %>
     <li>
      <%= check_box_tag "tag_ids[]", t.id %>
      <%= t.tname %>
    </li>
   <% end %>

<%= form_tag({controller:"links",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
<% end %>

<%= link_to "新規保存へ", new_link_path %>

<div class="links-container">
  <% @links.each do |t| %>
    <div class="links">
      <%= t.folder_id %>
      <%= t.url %>
      <%= t.title %>
      <%= t.memo %>
    </div>
    <div style="display: flex; gap: 10px;"> 
      <%= button_to "詳細へ", link_path(t.id), method: :get %>
      <%= button_to "編集する", edit_link_path(t.id), method: :get %>
      <%= button_to "削除する", link_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/links/new.html.erb
<h1>linfo</h1>
<h3>新規保存</h3>
<%= form_for @link do |f| %>

  <div class="field">
    <%= f.label :保存するURL %>
    <%= f.text_field :url, :size => 30 %>
  </div>

   <div class="field">
    <%= f.label :保存先  %>
    <%= f.select :folder_id, 
    [["選択肢１", "選択肢１"], 
    ["選択肢２", "選択肢２"], 
    ["選択肢３", "選択肢３"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 30 %>
  </div>

   <div class="field">
    <%= f.label :メモ  %>
    <%= f.text_area :memo, :size => "30x2" %>
  </div>

   <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tname) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>

    <%= f.submit "保存する" %>
<% end %>

<%= link_to "一覧に戻る", links_path %>

app/views/links/show.html.erb
<h1>linfo</h1>
<h3>詳細</h3>
<div class="link">
  <p><%= @link.url %></p>
  <p><%= @link.title %></p>
  <p><%= @link.memo %></p>
  <p><%= @link.created_at %></p>
  <% @link.tags.each do |tag| %>
    <span><%= tag.tname %></span>
  <% end %>
</div>

<%= link_to "編集する", edit_link_path(@link.id) %>
<%= link_to "一覧に戻る", links_path %>

app/views/statics/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>